### ISSUE TITLE
🦈

### ISSUE THREAD

**Issue by FilipNest** [lovedaybrooke/gender-decoder#7]
I got an amusing: "sharks support understanding" message with this (see below) and was puzzled so found you're using the word "shar" in the feminine list. I'm guessing this is part of "share"? Or "sharing"? Not sure. Either way "sharks" should probably not come up. Though they're great. (We're a digital agency building things for wildlife conservation, hence the sharks!).

![image](https://user-images.githubusercontent.com/4625324/47997643-75ee6580-e0f4-11e8-816f-f1e29c273531.png)

**Comment by lovedaybrooke** [comment]
Ahaha, I love it. My favourite parallel universe is the one where sharks are feminine-coded.

(Fixed now :) )
